version: '3'

services:
  fileupload:
    build:
      context: ./fileupload-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    restart: unless-stopped
    networks:
      - backend

  bar:
    build:
      context: ./bar-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - backend

  reverse-proxy:
    image: nginx:1.17.6-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy:/etc/nginx
    networks:
      - backend

networks:
  backend: